[k3s-cluster]
#k3s-cluster ansible_host=localhost ansible_port=2222
k3s-cluster ansible_host=51.250.32.193

[k3s-cluster:vars]
ansible_user=ansible
ansible_ssh_private_key_file=./ansible_key
ansible_ssh_common_args="-o StrictHostKeyChecking=no"
ansible_become=yes