- name: Установка однонодового k3s cluster
  hosts: k3s-cluster
  become: true

  tasks:
    - name: Обновление списка пакетов
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Установка пакетов
      ansible.builtin.apt:
          name:
            - curl
          state: present
    - name: Скачивание и установка k3s
      ansible.builtin.shell: |
          curl -sfL https://get.k3s.io |  sh -
      args:
          creates: /etc/rancher/k3s
      register: k3s_install

    - name: Запуск кластера
      ansible.builtin.shell: |
        systemctl start k3s
      register: k3s_start
    - name: Скачивание и установка helm
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm
      register: helm_install

    - name: Добавление Harbor
      ansible.builtin.shell: |
          helm repo add harbor https://helm.goharbor.io
          helm repo update
      args:
        creates: /root/.cache/helm/repository/harbor-index.yaml
      register: harbor_repo_add
    - name: Создание namespace для Harbor
      ansible.builtin.command:
        cmd: kubectl create namespace harbor --kubeconfig /etc/rancher/k3s/k3s.yaml
      register: create_ns
      failed_when: false

    - name: Установка Harbor
      ansible.builtin.shell: |
        helm install harbor harbor/harbor \
          --namespace harbor \
          --kubeconfig /etc/rancher/k3s/k3s.yaml \
          --set expose.type=nodePort \
          --set expose.tls.enabled=false \
          --set externalURL=http://{{ ansible_default_ipv4.address }}:30002
      register: harbor_install
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      failed_when: false

    - name: Добавление репозитория Istio
      ansible.builtin.shell: |
        /usr/local/bin/helm repo add istio https://istio-release.storage.googleapis.com/charts
        /usr/local/bin/helm repo update

    - name: Создание namespace для Istio
      ansible.builtin.command:
        cmd: kubectl create namespace istio-system --kubeconfig /etc/rancher/k3s/k3s.yaml
      failed_when: false

    - name: Установка istio-base
      ansible.builtin.shell: |
        /usr/local/bin/helm install istio-base istio/base -n istio-system \
        --kubeconfig /etc/rancher/k3s/k3s.yaml
      failed_when: false
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Установка istiod
      ansible.builtin.shell: |
        /usr/local/bin/helm install istiod istio/istiod -n istio-system \
          --kubeconfig /etc/rancher/k3s/k3s.yaml \
          --wait
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml