- name: Установка однонодового k3s cluster
  hosts: k3s-cluster
  become: true

  tasks:
    - name: Обновление списка пакетов
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Установка пакетов
      ansible.builtin.apt:
          name:
            - curl
          state: present
    - name: Скачивание и установка k3s
      ansible.builtin.shell: |
          curl -sfL https://get.k3s.io | INSTALL_K3S_SKIP_ENABLE=true sh -
      args:
          creates: /usr/local/bin/k3s
      register: k3s_install

    - name: Запуск K3s сервера в фоновом режиме
      ansible.builtin.shell: |
        nohup /usr/local/bin/k3s server \
          --bind-address=0.0.0.0 \
          --https-listen-port=6443 \
          > /var/log/k3s.log 2>&1 &
      args:
        creates: /var/lib/rancher/k3s/server/token
      register: k3s_start
      async: 10
      poll: 0

    - name: Снятие taint с control-plane
      ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/master-
      register: taint_result

    - name: Скачивание и установка helm
      ansible.builtin.shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm
      register: helm_install

    - name: Добавление Harbor
      ansible.builtin.shell: |
          /usr/local/bin/helm repo add harbor https://helm.goharbor.io
          /usr/local/bin/helm repo update
      args:
        creates: /root/.cache/helm/repository/harbor-index.yaml
      register: harbor_repo_add
