apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-core-abort
  namespace: harbor
spec:
  hosts:
    - "*"
  gateways:
    - harbor-gateway
  http:
    - match:
        - uri:
            prefix: /api/
      fault:
        abort:
          percentage:
            value: 100
          httpStatus: 500
      route:
        - destination:
            host: harbor-core
            port:
              number: 80
    - route:
        - destination:
            host: harbor-portal
            port:
              number: 80